import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/FooterComponent";
import FooterComponent from "@/components/footer/FooterComponent";
import Navbar from "@/components/navigation/NavbarComponent";
import NavbarComponent from "@/components/navigation/NavbarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <NavbarComponent/>
      <body className="min-h-full flex flex-col">{children}</body>
      <FooterComponent/>
    </html>
  );
}
